### PR TITLE
New schema file phone_bluetooth_devices_scanned added.

### PR DESCRIPTION
**Pull request by this-Aditya**

### CODE REVIEW

**Comment by this-Aditya** [comment]
The CI error it is giving is `bytearray` not being recognised. Should I change type to `bytes`and configure it like that to pass the CI.

**Comment by this-Aditya** [comment]
@afolarin @blootsvoets Updated the schema.

**Comment by this-Aditya** [comment]
Do I need to Update android_phone-1.0.0 again in this pull request? As I have done it in another pr which contains changes to both `phone_bluetooth_devices_scannned` and `android_phone-1.0.0`.

**Review by yatharthranjan — COMMENTED** [review]
Can we add a key to denote if the bluetooth device is paired (or bonded)? It would be very useful to differentiate between paired and unpaired devices for behavioural analyses.

**Comment by this-Aditya** [comment]
Hi @yatharthranjan, this pull request looks messy and is also outdated. I have created a new one [here](Hi @yatharth, this pull request looks messy and is also outdated. I have created a new one here -> https://github.com/RADAR-base/RADAR-Schemas/pull/360) with the new suggestions.

**Pull request closed without merging**
