### PR TITLE
Release 0.6.1

### PR DESCRIPTION
**Pull request by yatharthranjan**
- Fix Maven publication
- Fix Logger in dockerfile
- Add VAS and ERS to aRMTspecs

### CODE REVIEW

**Review by mpgxvii — APPROVED** [review]
LGTM

**Comment by blootsvoets** [comment]
The gradle plugin version looks unintentional...

**Comment by yatharthranjan** [comment]
Yes, that was the highest version on the [gradle plugin portal](https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro) apart from 0.99.99 (I think to prompt users to migrate to 1.+ ver)

**Comment by blootsvoets** [comment]
Ah yes, indeed. I did migrate it as part of https://github.com/RADAR-base/RADAR-Schemas/pull/246, could you take a look at that?

**Pull request merged**
