### PR TITLE
Mobovi TicWatch schemas

### PR DESCRIPTION
**Pull request by danjjl**
Mobivi TicWatch Schemas to record:

- PPG (2 channels)
- ACC (3 channels)
- GYR (3 channels)

Additionally information :
- battery level
- server NTP time status
-  device version

### CODE REVIEW

**Comment by danjjl** [comment]
I specified the UTC timestamps and doubles in ms.
It seems most other schemas use UTC timestamps as doubles in s.
Does this mean the integer part of the double is a UTC in seconds with ms after the decimal point?

**Comment by Bdegraaf1234** [comment]
Hi @danjjl 

Sorry for the wait, in the future you can request a review from me or another contributor to get the ball rolling.

**Review by Bdegraaf1234 — COMMENTED** [review]
My first remark would be that we should merge this into `dev` rather than `master`.

Second, the code does not compile on the ci server. Please make sure that the command `./gradlew assemble` and `./gradlew check` both succeed before we can merge these changes.

Lastly, [testing the schemas locally](https://github.com/RADAR-base/RADAR-Schemas/tree/master#test-setup) would be appreciated.

**Comment by danjjl** [comment]
@Bdegraaf1234 close to having solved all errors. Any idea what should be done to solve this last one?

Still getting one which I have difficulty understanding:

```
org.opentest4j.AssertionFailedError: expected: <> but was: <Validation FAILED:
Failed to load configuration /home/dan/ownCloud/epilepsy/RADAR-Schemas/specifications/passive/ticwatch-1.0.0.yml


>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at app//org.radarbase.schema.validation.SpecificationsValidatorTest$passiveIsYml$1.invokeSuspend(SpecificationsValidatorTest.kt:52)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at app//kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.radarbase.schema.validation.SpecificationsValidatorTest.passiveIsYml(SpecificationsValidatorTest.kt:49)
	at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by Bdegraaf1234** [comment]
Hey @danjjl, it looks like you did not define your units. 

The units are defined [here](https://github.com/RADAR-base/RADAR-Schemas/blob/refs/heads/master/commons/catalogue/unit.avsc)

You can add some ( I think PPG does not exist, maybe make it a non-abbreviated version) and use the existing definitions where possible (G, RADIAN_PER_SEC are the first ones I saw)

**Comment by danjjl** [comment]
@Bdegraaf1234 I corrected units

**Comment by Bdegraaf1234** [comment]
@danjjl The tests are not running because of merge conflicts, can you resolve those?

**Comment by danjjl** [comment]
@Bdegraaf1234 should be good now

**Comment by Bdegraaf1234** [comment]
Hi Jonathan, it seems the tests are failing again, are they passing when you run `./gradlew check`?

**Comment by danjjl** [comment]
@Bdegraaf1234 applied a fix.
`./gradlew check` now runs locally

**Review by Bdegraaf1234 — APPROVED** [review]
Great!

**Pull request merged**
