### PR TITLE
Release 0.7.3

### PR DESCRIPTION
**Pull request by mpgxvii**
- Add new aRMT questionnaire specs
- Add DREEM device specifications
- Fix Garmin stress_level docs

### CODE REVIEW

**Comment by blootsvoets** [comment]
Added fixes for #272 and #281.

**Comment by baixiac** [comment]
Thanks, @blootsvoets and @yatharthranjan. I can confirm your fix in `radarbase/radar-schemas-tools:dev` works and the CI is now green 👍 :
https://github.com/RADAR-base/RADAR-Docker/actions/runs/1162322685

**Review by yatharthranjan — APPROVED** [review]
LGTM

**Review by nivemaham — APPROVED** [review]
LGTM

**Pull request merged**
